services:
  - type: web
    name: bingo-bot
    plan: free
    env: python
    region: singapore  # Choose closest to your users
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python run.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: OWNER_ID
        sync: false
      - key: ENV
        value: production
    healthCheckPath: /healthz
    autoDeploy: true
