services:
  - type: worker
    name: bingo-bot-worker
    env: python
    command: |
      if [ -f /tmp/t1x2y1_bot.lock ]; then
        rm /tmp/t1x2y1_bot.lock
      fi
      cd /opt/render/project/src && python -m t1x2y1.run
    plan: free
    region: singapore
    workingDirectory: /t1x2y1
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: OWNER_ID
        sync: false
    healthCheckPath: /healthz
    autoDeploy: true
